apiVersion: v1
kind: Secret
metadata:
  name: map-app-secret
  namespace: default
type: Opaque
stringData:
  IAM_USERNAME: username
  IAM_PASSWORD: password
  AWS_ACCESS_KEY_ID: access_key_id
  AWS_SECRET_ACCESS_KEY: secret_access_key