apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argo
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
    helm.sh/chart: argo-cd-3.11.1
  annotations:
    meta.helm.sh/release-name: argocd
    meta.helm.sh/release-namespace: argo
data:
  application.instanceLabelKey: argocd.argoproj.io/instance
  repositories: |
    - name: repo-ghe
      sshPrivateKeySecret:
        key: sshPrivateKey
        name: repo-ghe
      type: git
      url: git@ghe.tusimple.io:TuSimple/map-aws-infra.git

  url: 'https://argocd.example.com'
